package net.unicon.shibui.pac4j.authenticator;

import edu.internet2.tier.shibboleth.admin.ui.security.service.UserService;
import lombok.AllArgsConstructor;
import org.apache.commons.lang3.StringUtils;
import org.pac4j.core.context.WebContext;
import org.pac4j.core.credentials.Credentials;
import org.pac4j.core.credentials.TokenCredentials;
import org.pac4j.core.credentials.authenticator.Authenticator;
import org.pac4j.core.exception.CredentialsException;
import org.pac4j.core.profile.CommonProfile;

/**
 * Handles parsing the header tokens when using the Pac4J Header client
 */
@AllArgsConstructor
public class ShibuiPac4JHeaderClientAuthenticator implements Authenticator {
    private UserService userService;

    @Override
    public void validate(Credentials credentials, WebContext context) {
        {
            if (credentials instanceof TokenCredentials) {
                TokenCredentials creds = (TokenCredentials) credentials;
                String token = creds.getToken();
                if (StringUtils.isAllBlank(token)) {
                    throw new CredentialsException("Supplied token value in header was missing or blank");
                }
            } else {
                throw new CredentialsException("Invalid Credentials object generated by HeaderClient");
            }
            final CommonProfile profile = new CommonProfile();
            String token = ((TokenCredentials) credentials).getToken();
            profile.setId(token);
            profile.addAttribute("username", token);
            profile.setRoles(userService.getUserRoles(token));
            credentials.setUserProfile(profile);
        }
    }
}