server:
  use-forward-headers: true
  forward-headers-strategy: NATIVE
spring:
  profiles:
    include:
shibui:
  user-bootstrap-resource: file:/conf/users.csv
  roles: ROLE_ADMIN,ROLE_NONE,ROLE_USER,ROLE_ENABLE,ROLE_PONY
  pac4j-enabled: true
  pac4j:
    keystorePath: "/conf/samlKeystore.jks"
    keystorePassword: "changeit"
    privateKeyPassword: "changeit"
    serviceProviderEntityId: "https://unicon.net/test/shibui"
    serviceProviderMetadataPath: "/conf/sp-metadata.xml"
    identityProviderMetadataPath: "/conf/idp-metadata.xml"
    forceServiceProviderMetadataGeneration: true
    callbackUrl: "https://shibui.unicon.local/callback"
    maximumAuthenticationLifetime: 3600000
    postLogoutURL: "https://idp.unicon.local/idp/profile/Logout"
    simpleProfileMapping:
      username: urn:oid:0.9.2342.19200300.100.1.1
      firstName: urn:oid:2.5.4.42
      lastName: urn:oid:2.5.4.4
      email: urn:oid:0.9.2342.19200300.100.1.3
      groups: urn:oid:2.5.4.15  # businessCategory
      roles: urn:oid:1.3.6.1.4.1.5923.1.1.1.7  # eduPersonEntitlement