shibui:
  pac4j-enabled: true
  pac4j:
    simpleProfileMapping:
      username: urn:oid:0.9.2342.19200300.100.1.3
      firstName: givenName
      lastName: sn
      email: mail
      groupsName: urn:oid:1.3.6.1.4.1.5923.1.5.1.1 # attributeId - isMemberOf