shibui:
  pac4j-enabled: true
  pac4j:
    simpleProfileMapping:
      username: urn:oid:0.9.2342.19200300.100.1.3
      firstName: givenName
      lastName: sn
      email: mail
      groups: urn:oid:1.3.6.1.4.1.5923.1.5.1.1 # attributeId - isMemberOf
      roles:

#shibui:
## Default password must be set for the default user to be configured and setup
#  default-rootuser:root
## need to include the encoding for the password - be sure to quote the entire value as shown
#  default-password: "{noop}foopassword"
#  pac4j-enabled: true
#  pac4j:
#    keystorePath: "/etc/shibui/samlKeystore.jks"
#    keystorePassword: "changeit"
#    privateKeyPassword: "changeit"
#    serviceProviderEntityId: "https://idp.example.com/shibui"
#    serviceProviderMetadataPath: "/etc/shibui/sp-metadata.xml"
#    identityProviderMetadataPath: "/etc/shibui/idp-metadata.xml"
#    forceServiceProviderMetadataGeneration: false
#    callbackUrl: "https://localhost:8443/callback"
#    maximumAuthenticationLifetime: 3600000
#    requireAssertedRoleForNewUsers: false
#    saml2ProfileMapping:
#      username: urn:oid:0.9.2342.19200300.100.1.1
#      firstname: urn:oid:2.5.4.42
#      lastname: urn:oid:2.5.4.4
#      email: urn:oid:0.9.2342.19200300.100.1.3
#      groups: urn:oid:1.3.6.1.4.1.5923.1.5.1.1 # attributeId - isMemberOf
#      roles: --define name of the attribute containing the incoming user roles--