version: "3.7"

services:
  db:
    image: mariadb
    container_name: db
    environment:
      MYSQL_DATABASE: shibui
      MYSQL_USER: shibui
      MYSQL_PASSWORD: shibui
      MYSQL_ROOT_PASSWORD: root

    networks:
      - front
    ports:
      - 3306:3306
  shibui:
    image: unicon/shibui
    ports:
      - 8080:8080
      - 5005:5005
      - 8443:8443
    volumes:
      - ./conf:/conf
      - ./conf/application.yml:/application.yml
    networks:
      - front
    depends_on:
      - db
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
    container_name: mailhog
    networks:
      - front

networks:
  front:
    driver: bridge
