services:
  database:
    build:
      context: ../sqlServer
      dockerfile: ../sqlServer/docker/Dockerfile
    image: smoke-test_database
#    healthcheck:
#      test: mysql -u shibui --password=shibui shibui -e "select 1"
#      interval: 5s
#      retries: 5
#      start_period: 5s
#      timeout: 10s
#  shib-idp-ui:
#    depends_on:
#      database:
#        condition: service_healthy
        