version: "3.7"

  services:
    jenkins:
      build: ./jenkins
      container_name: jenkins
      command: --httpPort=9009 --prefix=/jenkins
      user: root
      ports:
        - "9009:9009"
        - "50000:50000"
      environment:
        JAVA_OPTS: "-Xmx2048m"
      volumes:
        - jenkins-data:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
    selenium-hub:
      image: selenium/hub:3.141.59-krypton
      container_name: selenium-hub
      ports:
        - "4444:4444"
    chrome:
      image: selenium/node-chrome:3.141.59-krypton
      volumes:
        - /dev/shm:/dev/shm
      depends_on:
        - selenium-hub
      environment:
        - HUB_HOST=selenium-hub
        - HUB_PORT=4444
    firefox:
      image: selenium/node-firefox:3.141.59-krypton
      volumes:
        - /dev/shm:/dev/shm
      depends_on:
        - selenium-hub
      environment:
        - HUB_HOST=selenium-hub
        - HUB_PORT=4444
