spring:
  profiles:
    include:
  datasource:
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://db:3306/shibui
    username: shibui
    password: shibui
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8443
  ssl:
    key-store: "/conf/keystore.p12"
    key-store-password: "changeit"
    keyStoreType: "PKCS12"
    keyAlias: "tomcat"
shibui:
  user-bootstrap-resource: file:/conf/users.csv
  roles: ROLE_ADMIN,ROLE_NONE,ROLE_USER,ROLE_PONY
custom:
  attributes:
    # Default attributes
    - name: eduPersonPrincipalName
      displayName: label.attribute-eduPersonPrincipalName
    - name: uid
      displayName: label.attribute-uid
    - name: mail
      displayName: label.attribute-mail
    - name: surname
      displayName: label.attribute-surname
    - name: givenName
      displayName: label.attribute-givenName
    - name: eduPersonAffiliation
      displayName: label.attribute-eduPersonAffiliation
    - name: eduPersonScopedAffiliation
      displayName: label.attribute-eduPersonScopedAffiliation
    - name: eduPersonPrimaryAffiliation
      displayName: label.attribute-eduPersonPrimaryAffiliation
    - name: eduPersonEntitlement
      displayName: label.attribute-eduPersonEntitlement
    - name: eduPersonAssurance
      displayName: label.attribute-eduPersonAssurance
    - name: eduPersonUniqueId
      displayName: label.attribute-eduPersonUniqueId
    - name: employeeNumber
      displayName: label.attribute-employeeNumber
  # Custom attributes
  overrides:
    # Default overrides
    - name: signAssertion
      displayName: label.sign-the-assertion
      displayType: boolean
      defaultValue: false
      helpText: tooltip.sign-assertion
      attributeName: http://shibboleth.net/ns/profiles/saml2/sso/browser/signAssertions
      attributeFriendlyName: signAssertions
    - name: dontSignResponse
      displayName: label.dont-sign-the-response
      displayType: boolean
      defaultValue: false
      helpText: tooltip.dont-sign-response
      attributeName: http://shibboleth.net/ns/profiles/saml2/sso/browser/signResponses
      attributeFriendlyName: signResponses
    - name: turnOffEncryption
      displayName: label.turn-off-encryption-of-response
      displayType: boolean
      defaultValue: false
      helpText: tooltip.turn-off-encryption
      attributeName: http://shibboleth.net/ns/profiles/encryptAssertions
      attributeFriendlyName: encryptAssertions
    - name: useSha
      displayName: label.use-sha1-signing-algorithm
      displayType: boolean
      defaultValue: false
      helpText: tooltip.usa-sha-algorithm
      persistType: string
      persistValue: shibboleth.SecurityConfiguration.SHA1
      attributeName: http://shibboleth.net/ns/profiles/securityConfiguration
      attributeFriendlyName: securityConfiguration
    - name: ignoreAuthenticationMethod
      displayName: label.ignore-any-sp-requested-authentication-method
      displayType: boolean
      defaultValue: false
      helpText: tooltip.ignore-auth-method
      persistType: string
      persistValue: 0x1
      attributeName: http://shibboleth.net/ns/profiles/disallowedFeatures
      attributeFriendlyName: disallowedFeatures
    - name: omitNotBefore
      displayName: label.omit-not-before-condition
      displayType: boolean
      defaultValue: false
      helpText: tooltip.omit-not-before-condition
      attributeName: http://shibboleth.net/ns/profiles/includeConditionsNotBefore
      attributeFriendlyName: includeConditionsNotBefore
    - name: responderId
      displayName: label.responder-id
      displayType: string
      defaultValue: null
      helpText: tooltip.responder-id
      attributeName: http://shibboleth.net/ns/profiles/responderId
      attributeFriendlyName: responderId
    - name: nameIdFormats
      displayName: label.nameid-format-to-send
      displayType: set
      helpText: tooltip.nameid-format
      defaultValues:
        - urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
        - urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
        - urn:oasis:names:tc:SAML:2.0:nameid-format:persistent
        - urn:oasis:names:tc:SAML:2.0:nameid-format:transient
      attributeName: http://shibboleth.net/ns/profiles/nameIDFormatPrecedence
      attributeFriendlyName: nameIDFormatPrecedence
    - name: authenticationMethods
      displayName: label.authentication-methods-to-use
      displayType: set
      helpText: tooltip.authentication-methods-to-use
      defaultValues:
        - https://refeds.org/profile/mfa
        - urn:oasis:names:tc:SAML:2.0:ac:classes:TimeSyncToken
        - urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport
      attributeName: http://shibboleth.net/ns/profiles/defaultAuthenticationMethods
      attributeFriendlyName: defaultAuthenticationMethods
    - name: forceAuthn
      displayName: label.force-authn
      displayType: boolean
      defaultValue: false
      helpText: tooltip.force-authn
      attributeName: http://shibboleth.net/ns/profiles/forceAuthn
      attributeFriendlyName: forceAuthn
logging:
  level:
    org.pac4j: "TRACE"
    org.opensaml: "INFO"
