custom:
  attributes:
  # Default attributes
    - name: eduPersonPrincipalName
      displayName: label.attribute-eduPersonPrincipalName
    - name: uid
      displayName: label.attribute-uid
    - name: mail
      displayName: label.attribute-mail
    - name: surname
      displayName: label.attribute-surname
    - name: givenName
      displayName: label.attribute-givenName
    - name: eduPersonAffiliation
      displayName: label.attribute-eduPersonAffiliation
    - name: eduPersonScopedAffiliation
      displayName: label.attribute-eduPersonScopedAffiliation
    - name: eduPersonPrimaryAffiliation
      displayName: label.attribute-eduPersonPrimaryAffiliation
    - name: eduPersonEntitlement
      displayName: label.attribute-eduPersonEntitlement
    - name: eduPersonAssurance
      displayName: label.attribute-eduPersonAssurance
    - name: eduPersonUniqueId
      displayName: label.attribute-eduPersonUniqueId
    - name: employeeNumber
      displayName: label.attribute-employeeNumber
  # Custom attributes

# The following contains a map of "relying party overrides".
# The structure of an entry is as follows:
# - name: The name of the entry. used to uniquely identify this entry.
#   displayName: This will normally be the label used when displaying this override in the UI
#   helpText: This is the help-icon hover-over text
#   persistType: Optional. If it is necessary to persist something different than the override's display type,
#                set that type here. For example, display a boolean, but persist a string.
#   persistValue: Required only when persistType is used. Defines the value to be persisted.
#   attributeName: This is the name of the attribute to be used in the xml. This is assumed to be a URI.
#   attributeFriendlyName: This is the friendly name associated with the above attributeName.
#
# It is imperative when defining these that the "displayType" and "persistType" are known types.
# Typos or unsupported values here will result in that override being skipped!
# Supported types are as follows: boolean, integer, string, set, list
# Note that "persistType" doesn't have to match "displayType". However, the only unmatching combination currently
# supported is a "displayType" of "boolean" and "persistType" of "string".
  overrides:
  # Default overrides
    - name: signAssertion
      displayName: Sign the Assertion
      displayType: boolean
      helpText: Sign Assertion
      attributeName:
      attributeFriendlyName:
    - name: signResponses
      displayName: Don't Sign the Response
      displayType: boolean
      helpText: Don't Sign Response
    - name: turnOffEncryption
      displayName: Turn Off Encryption of Response
      displayType: boolean
      helpText: Turn Off Encryption of Response
    - name: useSha
      displayName: Use SHA1 Signing Algorithm
      displayType: boolean
      helpText: Use SHA1 Signing Algorithm
      persistType: string
      persistValue: shibboleth.SecurityConfiguration.SHA1
    - name: ignoreAuthenticationMethod
      displayName: Ignore any SP-Requested Authentication Method
      displayType: boolean
      helpText: Ignore any SP-Requested Authentication Method
      persistType: string
      persistValue: 0x1
    - name: omitNotBefore
      displayName: Omit Not Before Condition
      displayType: boolean
      helpText: Omit Not Before Condition
    - name: responderId
      displayName: responderId
      displayType: string
      helpText: ResponderId
    - name: nameIdFormats
      displayName: nameIdFormats
      displayType: list
      helpText: Add NameID Format
      defaultValues:
        - urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
        - urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
        - urn:oasis:names:tc:SAML:2.0:nameid-format:persistent
        - urn:oasis:names:tc:SAML:2.0:nameid-format:transient
    - name: authenticationMethods
      displayName: authenticationMethods
      displayType: list
      helpText: Authentication Methods to Use
      defaultValues:
        - https://refeds.org/profile/mfa
        - urn:oasis:names:tc:SAML:2.0:ac:classes:TimeSyncToken
        - urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport
    - name: forceAuthn
      displayName: Force AuthN
      displayType: boolean
      helpText: Disallows use (or reuse) of authentication results and login flows that don't provide a real-time proof of user presence in the login process