version: "3.7"

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: shibui
      POSTGRES_PASSWORD: shibui
      POSTGRES_DB: shibui
    networks:
      - front
    ports:
      - 5432:5432
  shibui:
    image: unicon/shibui
    ports:
      - 8080:8080
      - 5005:5005
      - 8443:8443
      - 8000:8000
    volumes:
      - ./conf:/conf
      - ./conf/application.yml:/application.yml
    entrypoint: ["/usr/bin/java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000", "-jar", "app.war"]
    networks:
      - front
    depends_on:
      - db
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
    container_name: mailhog
    networks:
      - front

networks:
  front:
    driver: bridge